name: testsite99
favicon: null
layout_spectrum: 0.32677055010572076
typography_spectrum: 0.7251825691200793
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9762125650886446
  lightness: 0.29371461528353393
  saturation: 0.7007100365590304
  rhythmicContrast: 0.6811087776441127
purpose: []
