name: testsite99
favicon: null
layout_spectrum: 0.88064
typography_spectrum: 0.24789
title: "Gino's Food Delights"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#02070b'
    - '#7193af'
    - '#ded6c3'
    - '#007e10'
    - '#990000'
  brandStrength: 0.9762125650886446
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 0.6811087776441127
purpose: []
